FROM centos6_1:tiger
MAINTAINER  sunwang sunwang1101@aliyun.com
RUN  yum install -y pcre-devel wget net-tools gcc zlib zlib-devel make openssl-devel
ADD  http://nginx.org/download/nginx-1.8.0.tar.gz .
RUN  tar -zxf   nginx-1.8.0.tar.gz
RUN  mkdir -p /usr/local/nginx/
WORKDIR  nginx-1.8.0
RUN  ./configure --prefix=/usr/local/nginx && make && make install
RUN rm -f /usr/local/nginx/conf/nginx.conf
COPY nginx_conf /usr/local/nginx/conf/nginx.conf
EXPOSE 80
