__author__ = "sun wang"
#name = "my \tname is alex"
name = "my \tname is {name} and i am {year} old"
print(name.capitalize())
print(name.count("a"))
print(name.center(50,"-"))
print("my name is alex".encode("utf-8"))
print(name.endswith("ex"))
print(name.expandtabs(tabsize=30))
print(name.find('m'))
print(name[name.find("name"):9])
print(name.format(name='alex',year=31))
print(name.format_map({'name':'alex','year':12}))
print("abc12".isalnum())
print("abc12!".isalnum())
print("abcA1".isalpha())
print("21".isdecimal())
print ('1A1'.identifier())
print ('a1A'.islower())
print ('33.333'.isnumeric())
print ("  ".isspace())
print ('My Name Is'.istitle())
print ('My name is'.istitle())
print ('My name is'.title())
print (','.join(['1','2','3']))
name.translate()
name.rfind()
name.split()